WIP: upgrade to RN 0.56.0
After android app runs, Metro errors with:
error: bundling failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/babel-preset-react-native-stage-0/decorator-support.js
    at createDescriptor (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
    at items.map (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
    at presets (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
    at mergeChainOpts (/Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-chain.js:308:26)
    at /Users/stefanos/proj/a8c/rn/gutenberg-mobile/node_modules/@babel/core/lib/config/config-chain.js:271:7